### ISSUE TITLE
Can't use --ci for local builds

### ISSUE THREAD

**Issue by nathantomsic** [criblio/js2bin#11]

**Comment by ledbit** [comment]
Agreed. @nathantomsic can you please comment on what are you trying to do?

**Comment by nathantomsic** [comment]
The number of prebuilds available are pretty limited. I should be able to build a node version with my target from source if a prebuilt one is not available. However, --ci tries to upload them to github and then deletes everything.

**Comment by ledbit** [comment]
Agreed. @nathantomsic can you please comment on what are you trying to do?

**Comment by ledbit** [comment]
handled in `1.0.5`- you should now be able to use `js2bin --ci --cache --node=<version> --size=2MB`

**Comment by Autr** [comment]
I have done this, the compiled bin is available in the cache folder, but the build command still tries to download it...
